name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependencies
      run: npm install

    - name: run integration tests
      run: npm test

  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.SERVICE_ID }}
          api_key: ${{ secrets.RENDER_TOKEN }}
          wait_deploy: true
